# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_start_date', models.DateTimeField(verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xa5\xe6\x9c\x9f')),
                ('settlement_end_date', models.DateTimeField(verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xa5\xe6\x9c\x9f')),
                ('transaction_type', models.CharField(max_length=12, verbose_name=b'\xe4\xba\x8b\xe5\x8a\xa1\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('order_id', models.CharField(max_length=64, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95ID')),
                ('posted_date', models.DateTimeField(verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
                ('sku', models.CharField(max_length=64, verbose_name=b'sku')),
                ('quantity_purchased', models.IntegerField(default=0, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe6\x95\xb0')),
                ('price_amount', models.IntegerField(default=0, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe6\x80\xbb\xe4\xbb\xb7')),
                ('item_related_fee_amount', models.IntegerField(default=0, verbose_name=b'\xe9\xa1\xb9\xe7\x9b\xae\xe7\x9b\xb8\xe5\x85\xb3\xe7\x9a\x84\xe8\xb4\xb9\xe7\x94\xa8\xe9\x87\x91\xe9\xa2\x9d')),
                ('promotion_amount', models.IntegerField(default=0, verbose_name=b'\xe4\xbf\x83\xe9\x94\x80\xe9\x87\x91\xe9\xa2\x9d')),
                ('account', models.IntegerField(choices=[(1, b'admin')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='AccountData',
        ),
    ]
